car_rental/cars/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from car_rental.cars.views import *

app_name='cars'

urlpatterns = [
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

car_rental/core/urls.py
from django.urls import path
from car_rental.core.views import *

app_name='core'

urlpatterns = [
    path('', home, name='home'),
]

car_rental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('car_rental.core.urls', namespace='core')),
    path('veiculos/', include('car_rental.cars.urls', namespace='vehicles')),
    path('reservas/', include('car_rental.rental.urls', namespace='rental')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/core/models.py
from django.db import models

# Create your models here.

car_rental/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'home.html')

car_rental/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="ViajaBem" />
        <title>ViajaBem</title>
        <link rel="stylesheet"
              href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
        <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}" />
    </head>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <body>
        <div class="header">
            <div class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal">
                <a class="pure-menu-heading" href="{% url 'core:home' %}">ViajaBem</a>
                <ul>
                    <li class="pure-menu-selected">
                        <a href="{% url 'core:home' %}">Início</a>
                    </li>
                    <li>
                        <a href="{% url 'cars:index' %}">Veículos</a>
                    </li>
                    <li>
                        <a href="{% url 'rental:index' %}">Reservas</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content">
            {% if messages %}
                <div class="pure-g-r content-ribbon">
                    <aside class="pure-u-1" style="background-color: #2d3e50">
                        {% for message in messages %}<p>{{ message }}</p>{% endfor %}
                    </aside>
                </div>
            {% endif %}
            {% block content %}
            {% endblock content %}
            <div class="footer">ViajaBem - Desde 1986</div>
        </div>
        <script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js" />
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

car_rental/core/templates/home.html
{% extends "base.html" %}
{% block content %}
    <div class="splash">
        <div class="pure-g-r">
            <div class="pure-u-1">
                <div class="l-box splash-text">
                    <h1 class="splash-head">Bem-vindo à ViajaBem</h1>
                    <h2 class="splash-subhead">
                        Descubra uma nova forma de explorar o mundo com nossos 
                        veículos de lazer. Experiências únicas e inesquecíveis 
                        esperam por você.
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Aluguel Descomplicado</h4>
                    <h3>Alugue um veículo sem preocupações</h3>
                    <p>
                        Simplificamos o processo de aluguel de veículos para você. 
                        Com reservas rápidas, contratos claros e suporte 24/7, 
                        tornamos o aluguel de carros uma experiência descomplicada.
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="media/home/aluguel_descomplicado.jpg"
                         alt="Aluguel Descomplicado"
                         width="400"
                         height="250" />
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="media/home/clientes_satisfeitos.jpg"
                         alt="Clientes Satisfeitos"
                         width="400"
                         height="250" />
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Clientes Satisfeitos</h4>
                    <h3>Confie em nossa reputação</h3>
                    <p>
                        Centenas de clientes satisfeitos já confiaram em nossos 
                        serviços. Com avaliações positivas e feedbacks elogiosos, 
                        somos a escolha confiável para o aluguel de veículos. 
                        Junte-se a eles!
                    </p>
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Frota de Qualidade</h4>
                    <h3>Veículos modernos e bem-mantidos</h3>
                    <p>
                        Oferecemos uma ampla seleção de veículos de qualidade 
                        para atender às suas necessidades. Nossa frota é composta 
                        por carros modernos, inspecionados regularmente e sempre 
                        prontos para proporcionar uma viagem confortável e segura.
                    </p>
                </div>
            </div>
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="media/home/frota_qualidade.jpg"
                         alt="Frota de Qualidade"
                         width="400"
                         height="250" />
                </div>
            </div>
        </div>
        <div class="pure-g-r content-ribbon">
            <div class="pure-u-1-3">
                <div class="l-box">
                    <img src="media/home/20anos_experiencia.jpeg"
                         alt="Tradição em Aluguel de Veículos"
                         width="400"
                         height="250" />
                </div>
            </div>
            <div class="pure-u-2-3">
                <div class="l-box">
                    <h4 class="content-subhead">Tradição em Aluguel de Veículos</h4>
                    <h3>Mais de 20 anos de excelência</h3>
                    <p>Com uma sólida história de mais de duas décadas no mercado, 
                        somos uma empresa de aluguel de veículos com tradição e 
                        experiência. Conte conosco para receber um serviço 
                        excepcional e garantia de satisfação.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}