car_rental/rental/urls.py
from django.urls import path
from car_rental.rental.views import *

app_name='rental'

urlpatterns = [
    path('', index, name='index'),
    path('rental_modal/', rental_modal, name='rental_modal'),
]

car_rental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('car_rental.core.urls', namespace='core')),
    path('veiculos/', include('car_rental.cars.urls', namespace='vehicles')),
    path('reservas/', include('car_rental.rental.urls', namespace='rental')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_rental/rental/models.py
from django.utils import timezone
from django.utils.timezone import timedelta
from django.core.exceptions import ValidationError
from django.db import models
from car_rental.cars.models import Car


class Rental(models.Model):
    
    STATUS_CHOICES = (
        (0, 'Pendente'),
        (1, 'Aprovada'),
        (2, 'Cancelada')
    )
    status = models.IntegerField(
        'Situação',
        choices=STATUS_CHOICES, 
        default=0,
    )

    def get_default_car():
        return Car.objects.first()

    car = models.ForeignKey(
        Car, verbose_name='Carro',
        on_delete=models.CASCADE,
        related_name='rentals',
        default=get_default_car
    )

    pick_up_date = models.DateTimeField(
        'Data de Retirada',
        default=timezone.now()
    )
    drop_off_date = models.DateTimeField(
        'Data de Entrega',
        default=timezone.now() + timedelta(days=1)
    )
    
    observations = models.TextField('Observações', max_length=100, blank=True)

    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    def __str__(self):
        return("Reserva #" + str(self.pk))
    
    # def active(self):
    #     self.status = 1
    #     self.save()
    #
    # def cancelled(self):
    #     self.status = 2
    #     self.save()

    # def is_approved(self):
    #     return self.status == 1

    class Meta:
        verbose_name = 'Aluguel'
        verbose_name_plural = 'Aluguéis'
        ordering = ['car','-pick_up_date','drop_off_date']
    
    def clean(self):
        if not self._state.adding: # caso o user esteja fazendo UPDATE:
            original_instance = Rental.objects.get(pk=self.pk)

            for field in self._meta.fields:
                field_name = field.name
                current_value = getattr(self, field_name)
                original_value = getattr(original_instance, field_name)
                # Só poderá editar o STATUS, e nenhum outro campo
                if field_name != 'status' and current_value != original_value:
                    field_verbose_name = field.verbose_name
                    raise ValidationError(f"O campo '{field_verbose_name}' não pode ser alterado.")
        else:
            self.validate_car_availability()
            self.validate_date()
            self.validate_date_overlap()

    def validate_date(self):
        current_datetime = timezone.now()
        if not self.pick_up_date < self.drop_off_date:
            raise ValidationError('Não foi possível realizar a reserva. \
                                  A data de retirada não pode ser maior que a \
                                  data de devolução.')
        
        if not self.pick_up_date > current_datetime:
            raise ValidationError('Não foi possível realizar a reserva. \
                                  A data de retirada não pode ser anterior ao \
                                  dia de hoje.')

    def validate_car_availability(self):
        if self.car.status == 2:
            raise ValidationError('Não foi possível realizar a reserva. \
                                  O veículo selecionado está em manutenção. \
                                  Por favor, selecione outro veículo') 

    def validate_date_overlap(self):

        existing_rentals = Rental.objects.filter(car=self.car).exclude(status=2)

        for rental in existing_rentals:
            if ((rental.pick_up_date <= self.pick_up_date <= rental.drop_off_date) or
                (rental.pick_up_date <= self.drop_off_date <= rental.drop_off_date) or
                (self.pick_up_date <= rental.drop_off_date <= self.drop_off_date)):
                    
                raise ValidationError('O veículo já está ocupado nessa data. \
                                      Por favor, selecione outra data')
    

car_rental/rental/forms.py
from django import forms

from car_rental.rental.models import Rental


class DateTimeInput(forms.DateTimeInput):
    input_type = 'datetime-local'


class CarRentalForm(forms.ModelForm):

    class Meta:
        model = Rental
        fields = '__all__'
        exclude = ['status']
        widgets = {
            'pick_up_date': DateTimeInput(),
            'drop_off_date': DateTimeInput(),
        }

    

car_rental/rental/views.py
from django.shortcuts import render, redirect
from car_rental.rental.forms import CarRentalForm
from django.contrib import messages
from django.http import JsonResponse

from .models import *


def index(request):
    rentals = Rental.objects.all()
    template_name = 'rental/index.html'
    context = {
        'rentals': rentals,
    }
    return render(request, template_name, context)


def rental_modal(request):
    template_name = 'rental/rental_modal.html'
    context = {}
    if request.method == 'POST':
        form = CarRentalForm(request.POST or None)
        if form.is_valid():
            form.save()
            messages.success(request, 'Sua reserva foi feita com sucesso.')
            return redirect('cars:index')
        else:
            for error in form.errors:
                messages.error(request, form.errors[error])
                return redirect('cars:index')
    else:
        form = CarRentalForm()
    context['form'] = form
    return render(request, template_name, context)

car_rental/rental/templates/rental/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <div class="l-box">
                <h4 class="content-subhead">Listagem de Reservas</h4>
                <p>Abaixo o nosso catalogo de veículos disponiveis para reservar.</p>
                {% comment %} <h4 class="content-subhead">Selecione a data desejada:</h4>
                <form action="#">
                    <div style="justify-content: space-between;
                    align-items: center">
                        <label for="pickupdate">Data de retirada:</label>
                        <input type="datetime-local" id="pickupdate" name="birthday">
                    </div>
                    <div>
                        <label for="pickupdate">Data de devolução:</label>
                        <input type="datetime-local" id="pickupdate" name="birthday">
                    </div>
                    <input type="submit" label"Filtrar">
                </form> {% endcomment %}
            </div>
        </div>
    </div>
    <div class="rental-table">
        <table class="pure-table pure-table-horizontal w-100">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Status</th>
                    <th>Veículo</th>
                    <th>Data de retirada</th>
                    <th>Data de devolução</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                {% for rental in rentals %}
                    <tr>
                        <td>{{ rental }}</td>
                        <td>{{ rental.get_status_display }}</td>
                        <td>{{ rental.car }}</td>
                        <td>{{ rental.pick_up_date }}</td>
                        <td>{{ rental.drop_off_date }}</td>
                        <td>ícones</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3">Nenhuma reserva registrada no momento</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

car_rental/rental/templates/rental/rental_modal.html
{% load static %}
<div class="modal fade"
     id="carRental"
     data-bs-backdrop="static"
     data-bs-keyboard="false"
     tabindex="-1"
     aria-labelledby="staticBackdropLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Reserva</h1>
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form 
                    action="{% url 'rental:rental_modal' %}"
                    id="rentalForm"
                    class="pure-form pure-form-stacked" 
                    method="post"
                >
                    {% csrf_token %}
                    <fieldset>
                        {{ form.non_field_errors }}
                        {% for field in form %}
                            <div class="pure-control-group">
                                {{ field.label_tag }}
                                {{ field }}
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Reservar</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Sair</button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>